services:
  console:
    env_file:
      - env/console.dev.env

  store:
    build:
      args:
        NEXT_PUBLIC_API_BASE_URL: http://api-gateway:5055/api
        NEXT_PUBLIC_API_SOCKET_URL: http://api-gateway:5055
        NEXT_PUBLIC_STORE_DOMAIN: http://store:3000
        NEXTAUTH_URL: http://store:3000
    env_file:
      - env/store.dev.env
