const categories = [
  {
    _id: '61b0d3975741dd2e949d53f9',
    name: { en: 'Sports & Fitness', fr: 'Sport & Remise en forme' },
    type: { en: 'Sports & Fitness', fr: 'Sport & Remise en forme' },
    icon: 'https://i.ibb.co/qNCvxT0/dumbbell.png',
    status: 'ACTIVE',
    children: [],
  },
  {
    _id: '61b0d3975741dd2e949d5407',
    name: { en: 'Cooking Essentials', fr: 'Essentiels de cuisine' },
    type: 'Grocery',
    icon: 'https://i.ibb.co/hBv30Rt/frying-pan.png',
    status: 'Show',
    children: [],
  },
  {
    _id: '61b0d3975741dd2e949d5408',
    name: { en: 'Fresh Seafood', fr: 'Fruits de mer frais' },
    type: 'Grocery',
    icon: 'https://i.ibb.co/pfscwF4/shrimp.png',
    status: 'Show',
    children: [],
  },
  {
    _id: '61b0d3975741dd2e949d5409',
    name: { en: 'Fruits & Vegetable', fr: 'Fruits & Légumes' },
    type: 'Grocery',
    icon: 'https://i.postimg.cc/RZ275n3f/cabbage.png',
    status: 'Show',
    children: [],
  },
  {
    _id: '61b0d3975741dd2e949d53fc',
    name: { en: 'Baby Care', fr: 'Soins pour bébé' },
    type: 'Health Care',
    icon: 'https://i.postimg.cc/QNqrnQBB/baby.png',
    status: 'Show',
    children: [],
  },
  {
    _id: '61b0d3975741dd2e949d5404',
    name: { en: 'Milk & Dairy', fr: 'Lait & Produits Laitiers' },
    type: 'Grocery',
    icon: 'https://i.ibb.co/181Qpm8/milk.png',
    status: 'Show',
    children: [],
  },
  {
    _id: '61b0d3975741dd2e949d53fa',
    name: { en: 'Beauty & Health', fr: 'Beauté & Santé' },
    type: 'Health Care',
    icon: 'https://i.postimg.cc/gjz1P7wx/beauty.png',
    status: 'Show',
    children: [],
  },
  {
    _id: '61b0d3975741dd2e949d53ff',
    name: { en: 'Snacks & Instant', fr: 'Snacks & Instantané' },
    type: 'Grocery',
    icon: 'https://i.ibb.co/HT7c6VT/chips.png',
    status: 'Show',
    children: [],
  },
  {
    _id: '61b0d3975741dd2e949d5401',
    name: { en: 'Sauces & Pickles', fr: 'Sauces & Cornichons' },
    type: 'Grocery',
    icon: 'https://i.postimg.cc/mk09xvk4/chili-sauce.png',
    status: 'Hide',
    children: [],
  },
  {
    _id: '61b0d3975741dd2e949d53fd',
    name: { en: 'Household Tools', fr: 'Outils ménagers' },
    type: 'Home Accessories',
    icon: 'https://i.ibb.co/rdY6zL0/cleaner.png',
    status: 'Show',
    children: [],
  },
  {
    _id: '61b0d3975741dd2e949d5400',
    name: { en: 'Jam & Jelly', fr: 'Confitures & Gelées' },
    type: 'Grocery',
    icon: 'https://i.postimg.cc/rmLvfsMC/strawberry-jam-1.png',
    status: 'Show',
    children: [],
  },
  {
    _id: '61b0d3975741dd2e949d53fe',
    name: { en: 'Biscuits & Cakes', fr: 'Biscuits & Gâteaux' },
    type: 'Grocery',
    icon: 'https://i.postimg.cc/0jVF5Cmc/cookie.png',
    status: 'Show',
    children: [],
  },
  {
    _id: '61b0d3975741dd2e949d5402',
    name: { en: 'Honey', fr: 'Miel' },
    type: 'Grocery',
    icon: 'https://i.postimg.cc/65JSfy6H/honey-1.png',
    status: 'Hide',
    children: [],
  },
  {
    _id: '61b0d3975741dd2e949d5405',
    name: { en: 'Drinks', fr: 'Boissons' },
    type: 'Grocery',
    icon: 'https://i.ibb.co/Dz8LKDX/soft-drink.png',
    status: 'Show',
    children: [],
  },
  {
    _id: '61b0d3975741dd2e949d53fb',
    name: { en: 'Pet Care', fr: 'Soins pour animaux' },
    type: 'Grocery',
    icon: 'https://i.postimg.cc/RVVzrWfg/cat.png',
    status: 'Show',
    children: [],
  },
  {
    _id: '61b0d3975741dd2e949d5406',
    name: { en: 'Breakfast', fr: 'Petit déjeuner' },
    type: 'Grocery',
    icon: 'https://i.ibb.co/dgPzSt7/bagel.png',
    status: 'Hide',
    children: [],
  },
  {
    _id: '61b0d3975741dd2e949d540a',
    name: { en: 'Fish & Meat', fr: 'Poisson & Viande' },
    type: 'Grocery',
    icon: 'https://i.ibb.co/y0zXYj5/carp-fish.png',
    status: 'Show',
    children: [],
  },
  {
    _id: '61b0d3975741dd2e949d5403',
    name: { en: 'Organic Food', fr: 'Aliments Bio' },
    type: 'Grocery',
    icon: 'https://i.ibb.co/xmGhNRF/apple.png',
    status: 'Show',
    children: [],
  },
];

export default categories;